-- The Grand Algorithm — Supabase schema
-- Run once in the SQL editor of a fresh project, then run seed.sql
-- (generated by scripts/gen-seed.mjs from public/data/journey*.json).
--
-- See .claude/skills/supabase-sync/SKILL.md for the invariants this schema
-- must uphold: idempotent upserts, XP always server-derived, never forgeable.

-- ── Reference data ──────────────────────────────────────────────────────
-- Not user data: no RLS. Lets the XP triggers below look up a problem's
-- XP value without trusting anything the client sends. Populated by seed.sql.
create table if not exists problems (
  journey_id smallint not null,
  slug text not null,
  xp int not null,
  difficulty text not null check (difficulty in ('easy', 'medium', 'hard')),
  primary key (journey_id, slug)
);
grant select on problems to anon, authenticated;

-- ── User data ────────────────────────────────────────────────────────────
create table if not exists user_progress (
  user_id uuid references auth.users not null,
  journey_id smallint not null,
  problem_slug text not null,
  solved_at timestamptz not null default now(),
  seconds_taken int,
  starred boolean not null default false,
  primary key (user_id, journey_id, problem_slug)
);

-- Append-only log: streak, ghost-ship schedule, unlocks, and item drops all
-- derive from this, never from a stored counter (see the sync-bible skill).
-- `id` is client-generated so retries from the offline queue are idempotent.
create table if not exists user_events (
  id uuid primary key,
  user_id uuid references auth.users not null,
  event_type text not null check (
    event_type in ('solve', 'boss_win', 'ghost_win', 'freeze_used', 'quiz_pass', 'chest', 'haste_bonus')
  ),
  ref_slug text,
  happened_at timestamptz not null default now()
);

create table if not exists user_meta (
  user_id uuid primary key references auth.users,
  display_name text,
  leetcode_username text,
  items jsonb not null default '{}',
  total_xp int not null default 0,
  updated_at timestamptz not null default now()
);

-- ── Row Level Security: every user only ever touches their own rows ─────
alter table user_progress enable row level security;
alter table user_events enable row level security;
alter table user_meta enable row level security;

create policy "select own progress" on user_progress for select using (auth.uid() = user_id);
create policy "insert own progress" on user_progress for insert with check (auth.uid() = user_id);
create policy "update own progress" on user_progress for update using (auth.uid() = user_id);

-- Append-only: select + insert only, no update/delete policies at all.
create policy "select own events" on user_events for select using (auth.uid() = user_id);
create policy "insert own events" on user_events for insert with check (auth.uid() = user_id);

create policy "select own meta" on user_meta for select using (auth.uid() = user_id);
create policy "insert own meta" on user_meta for insert with check (auth.uid() = user_id);
create policy "update own meta" on user_meta for update using (auth.uid() = user_id);

-- total_xp is server-derived only (see trigger below). Column-level privilege
-- blocks clients from setting it directly even though the row-level policy
-- above would otherwise allow updating their own row.
revoke update on user_meta from authenticated;
grant update (display_name, leetcode_username, items, updated_at) on user_meta to authenticated;

-- ── XP is always recomputed server-side from the logs, never trusted ────
-- from the client (golden rule: cross-device resume is sacred). Mirrors
-- src/lib/xp.ts totalXp() exactly: solved-problem xp + event bonuses
-- (ghost_win +150, chest ref 'xp' +50, haste_bonus + the referenced
-- problem's xp, where ref_slug is "journeyId:slug").
create or replace function recompute_total_xp() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  target_user uuid := coalesce(new.user_id, old.user_id);
  computed int;
begin
  select coalesce(sum(pr.xp), 0) into computed
  from user_progress up
  join problems pr on pr.journey_id = up.journey_id and pr.slug = up.problem_slug
  where up.user_id = target_user;

  computed := computed + coalesce((
    select sum(
      case
        when e.event_type = 'ghost_win' then 150
        when e.event_type = 'chest' and e.ref_slug = 'xp' then 50
        when e.event_type = 'haste_bonus' and e.ref_slug is not null then coalesce((
          select pr2.xp from problems pr2
          where pr2.journey_id = split_part(e.ref_slug, ':', 1)::smallint
            and pr2.slug = split_part(e.ref_slug, ':', 2)
        ), 0)
        else 0
      end
    )
    from user_events e
    where e.user_id = target_user
  ), 0);

  insert into user_meta (user_id, total_xp) values (target_user, computed)
  on conflict (user_id) do update set total_xp = excluded.total_xp, updated_at = now();

  return coalesce(new, old);
end;
$$;

create trigger trg_recompute_xp_progress
  after insert or update or delete on user_progress
  for each row execute function recompute_total_xp();

create trigger trg_recompute_xp_events
  after insert or update or delete on user_events
  for each row execute function recompute_total_xp();

-- ── Idempotent merge RPCs (apply the same rules as src/sync/merge.ts) ────
-- Run as the caller (security invoker, the default) so RLS + the
-- auth.uid()-scoped inserts above apply naturally — these are not a
-- privilege-escalation path, just the merge logic living next to the data.

create or replace function merge_solves(p_solves jsonb) returns void
language plpgsql as $$
begin
  insert into user_progress (user_id, journey_id, problem_slug, solved_at, seconds_taken, starred)
  select
    auth.uid(),
    (elem->>'journey_id')::smallint,
    elem->>'problem_slug',
    (elem->>'solved_at')::timestamptz,
    (elem->>'seconds_taken')::int,
    coalesce((elem->>'starred')::boolean, false)
  from jsonb_array_elements(p_solves) as elem
  on conflict (user_id, journey_id, problem_slug) do update set
    solved_at = least(user_progress.solved_at, excluded.solved_at),
    -- least() ignores NULLs (only NULL if both are), matching the client's
    -- "min of non-null secondsTaken" merge rule in src/sync/merge.ts.
    seconds_taken = least(user_progress.seconds_taken, excluded.seconds_taken),
    starred = user_progress.starred or excluded.starred;
end;
$$;

-- Per-key max, the same "cautious cap" src/sync/merge.ts uses — summing
-- would double-count on redelivery and break idempotence.
create or replace function merge_items(p_items jsonb) returns void
language plpgsql as $$
declare
  merged jsonb;
begin
  insert into user_meta (user_id, items) values (auth.uid(), '{}'::jsonb)
  on conflict (user_id) do nothing;

  select jsonb_object_agg(
    key,
    greatest(
      coalesce((existing.items->>key)::int, 0),
      coalesce((p_items->>key)::int, 0)
    )
  )
  into merged
  from user_meta existing, jsonb_object_keys(existing.items || p_items) as key
  where existing.user_id = auth.uid();

  update user_meta set items = coalesce(merged, '{}'::jsonb), updated_at = now()
  where user_id = auth.uid();
end;
$$;

create or replace function set_meta(p_display_name text, p_leetcode_username text) returns void
language plpgsql as $$
begin
  insert into user_meta (user_id, display_name, leetcode_username)
  values (auth.uid(), p_display_name, p_leetcode_username)
  on conflict (user_id) do update set
    display_name = coalesce(p_display_name, user_meta.display_name),
    leetcode_username = coalesce(p_leetcode_username, user_meta.leetcode_username),
    updated_at = now();
end;
$$;

-- ── Leaderboard: definer functions expose only (display_name, xp) ───────
-- A security-invoker view over user_meta would show each caller only their
-- own row (their own RLS policy applies) — useless for a leaderboard. These
-- functions run as definer specifically so they can read every row, while
-- still never exposing user_id or email to the client.
create or replace function leaderboard_alltime() returns table(display_name text, total_xp int)
language sql security definer set search_path = public as $$
  select coalesce(display_name, 'Anonymous Pirate'), total_xp
  from user_meta
  order by total_xp desc
  limit 100;
$$;

create or replace function leaderboard_weekly() returns table(display_name text, total_xp int)
language sql security definer set search_path = public as $$
  with recent_progress as (
    select up.user_id, sum(pr.xp) as xp
    from user_progress up
    join problems pr on pr.journey_id = up.journey_id and pr.slug = up.problem_slug
    where up.solved_at >= now() - interval '7 days'
    group by up.user_id
  ),
  recent_events as (
    select e.user_id, sum(
      case
        when e.event_type = 'ghost_win' then 150
        when e.event_type = 'chest' and e.ref_slug = 'xp' then 50
        when e.event_type = 'haste_bonus' and e.ref_slug is not null then coalesce((
          select pr2.xp from problems pr2
          where pr2.journey_id = split_part(e.ref_slug, ':', 1)::smallint
            and pr2.slug = split_part(e.ref_slug, ':', 2)
        ), 0)
        else 0
      end
    ) as xp
    from user_events e
    where e.happened_at >= now() - interval '7 days'
    group by e.user_id
  )
  select coalesce(m.display_name, 'Anonymous Pirate') as display_name,
         coalesce(rp.xp, 0) + coalesce(re.xp, 0) as total_xp
  from user_meta m
  left join recent_progress rp on rp.user_id = m.user_id
  left join recent_events re on re.user_id = m.user_id
  where coalesce(rp.xp, 0) + coalesce(re.xp, 0) > 0
  order by total_xp desc
  limit 100;
$$;

revoke execute on function leaderboard_alltime() from public, anon;
revoke execute on function leaderboard_weekly() from public, anon;
grant execute on function leaderboard_alltime() to authenticated;
grant execute on function leaderboard_weekly() to authenticated;
