#!/usr/bin/env node
// Regenerates supabase/seed.sql from public/data/journey*.json so the
// `problems` reference table (used by the server-side XP triggers in
// supabase/schema.sql) always matches the shipped curriculum. Re-run after
// any curriculum edit (see .claude/commands/add-island.md) and paste the
// output into the Supabase SQL editor — it's a safe upsert, run anytime.
import { readFileSync, writeFileSync } from 'node:fs'

const escape = (s) => `'${s.replace(/'/g, "''")}'`

function loadJourney(name) {
  return JSON.parse(readFileSync(new URL(`../public/data/${name}.json`, import.meta.url), 'utf8'))
}

const journeys = [loadJourney('journey1'), loadJourney('journey2'), loadJourney('journey3')]

const rows = journeys.flatMap((j) =>
  j.problems.map((p) => `  (${j.id}, ${escape(p.slug)}, ${p.xp}, ${escape(p.difficulty)})`),
)

const sql = `-- Generated by scripts/gen-seed.mjs — do not edit by hand.
-- Seeds/updates the \`problems\` reference table from public/data/journey*.json.
-- Safe to re-run: upserts on (journey_id, slug).

insert into problems (journey_id, slug, xp, difficulty)
values
${rows.join(',\n')}
on conflict (journey_id, slug) do update set
  xp = excluded.xp,
  difficulty = excluded.difficulty;
`

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), sql)
console.log(`Wrote supabase/seed.sql with ${rows.length} problem rows.`)
